name: ukbkings
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base
  - mamba
  - radian
  - ca-certificates
  - certifi
  - openssl
  - r-tidyverse
  - r-devtools
  - r-disk.frame
  - tldr
  - r-arrow
  - conda
  - jbig
  - r-forcats
  - idna
  - r-desc
  - r-foreach
  - r-farver
  - backports.functools_lru_cache
  - ld_impl_linux-64
  - r-commonmark
  - libedit
  - r-dbplyr
  - r-testthat
  - bwidget
  - r-waldo
  - charset-normalizer
  - libstdcxx-devel_linux-64
  - fribidi
  - r-gtable
  - rchitect
  - r-httr
  - r-gh
  - xorg-libsm
  - r-rmarkdown
  - libnghttp2
  - _libgcc_mutex
  - r-rappdirs
  - r-jquerylib
  - gcc_linux-64
  - r-globals
  - xz
  - jpeg
  - gfortran_linux-64
  - font-ttf-inconsolata
  - r-jsonlite
  - r-dt
  - liblapack
  - r-git2r
  - aws-sdk-cpp
  - termcolor
  - aws-c-cal
  - r-modelr
  - r-doparallel
  - graphite2
  - ruamel_yaml
  - r-tidyselect
  - r-pkgbuild
  - binutils_impl_linux-64
  - libiconv
  - r-codetools
  - r-zip
  - tqdm
  - r-pillar
  - r-lobstr
  - r-lubridate
  - r-knitr
  - pip
  - r-xml2
  - zlib
  - make
  - setuptools
  - r-xopen
  - r-rex
  - r-remotes
  - r-lattice
  - r-ps
  - requests
  - r-tinytex
  - grpc-cpp
  - r-iterators
  - libgcc-devel_linux-64
  - r-mgcv
  - s2n
  - fonts-conda-ecosystem
  - r-munsell
  - ncurses
  - font-ttf-ubuntu
  - r-gargle
  - pysocks
  - r-callr
  - libblas
  - r-askpass
  - xorg-libxrender
  - r-xfun
  - xorg-kbproto
  - r-rcolorbrewer
  - r-bigassertr
  - orc
  - r-lazyeval
  - yaml-cpp
  - r-bit64
  - r-highr
  - aws-checksums
  - r-bit
  - r-dbi
  - lz4-c
  - r-broom
  - pixman
  - r-furrr
  - r-vroom
  - r-ggplot2
  - r-nlme
  - r-fansi
  - r-dtplyr
  - r-colorspace
  - glog
  - r-cellranger
  - urllib3
  - r-stringr
  - r-ids
  - pycparser
  - r-gitcreds
  - libxml2
  - xorg-libxt
  - aws-c-event-stream
  - arrow-cpp
  - libevent
  - r-ini
  - r-uuid
  - r-mass
  - r-fs
  - libgit2
  - font-ttf-source-code-pro
  - libsolv
  - r-digest
  - r-tidyr
  - r-bigreadr
  - r-brew
  - bzip2
  - r-rcmdcheck
  - libgfortran5
  - freetype
  - r-withr
  - pandoc
  - r-rprojroot
  - pcre
  - python
  - brotlipy
  - r-utf8
  - xorg-libx11
  - r-hms
  - r-reprex
  - libutf8proc
  - r-r6
  - reproc-cpp
  - xorg-xextproto
  - libdeflate
  - r-parallelly
  - colorama
  - r-matrix
  - r-fastmap
  - libstdcxx-ng
  - _openmp_mutex
  - libsanitizer
  - r-listenv
  - libbrotlienc
  - reproc
  - snappy
  - tk
  - re2
  - yaml
  - libmambapy
  - libnsl
  - r-rvest
  - xorg-libice
  - gcc_impl_linux-64
  - r-promises
  - shtab
  - r-usethis
  - r-rematch
  - gettext
  - pycosat
  - conda-package-handling
  - wheel
  - r-credentials
  - gxx_linux-64
  - r-googledrive
  - r-rversions
  - r-data.table
  - r-memoise
  - r-prettyunits
  - libbrotlidec
  - r-pkgconfig
  - libffi
  - r-readr
  - libgfortran-ng
  - lineedit
  - r-covr
  - r-readxl
  - r-dplyr
  - libprotobuf
  - libbrotlicommon
  - cairo
  - gfortran_impl_linux-64
  - r-stringi
  - aws-c-common
  - r-future
  - r-tibble
  - six
  - libgomp
  - r-viridislite
  - aws-c-io
  - harfbuzz
  - r-openssl
  - lzo
  - fontconfig
  - r-googlesheets4
  - kernel-headers_linux-64
  - r-processx
  - xorg-renderproto
  - xorg-xproto
  - pango
  - r-assertthat
  - r-selectr
  - libmamba
  - r-cpp11
  - libwebp-base
  - libarchive
  - r-haven
  - libxcb
  - r-sessioninfo
  - gxx_impl_linux-64
  - curl
  - libev
  - r-future.apply
  - cffi
  - r-sys
  - r-lifecycle
  - r-fst
  - numpy
  - binutils_linux-64
  - r-isoband
  - r-roxygen2
  - r-rematch2
  - sqlite
  - readline
  - libtiff
  - r-benchmarkme
  - r-rlang
  - libcurl
  - libopenblas
  - r-whisker
  - r-pkgload
  - r-crayon
  - pybind11-abi
  - r-clipr
  - libzlib
  - r-glue
  - r-rstudioapi
  - r-htmltools
  - pyopenssl
  - libpng
  - r-purrr
  - pcre2
  - r-yaml
  - r-progress
  - r-magrittr
  - libthrift
  - r-base64enc
  - sysroot_linux-64
  - r-brio
  - gsl
  - wcwidth
  - backports
  - r-praise
  - libglib
  - libssh2
  - abseil-cpp
  - python_abi
  - r-later
  - r-gert
  - xorg-libxext
  - r-crosstalk
  - r-evaluate
  - icu
  - r-benchmarkmedata
  - r-diffobj
  - r-blob
  - sed
  - r-rcpp
  - r-tzdb
  - r-cli
  - r-mime
  - r-generics
  - libuuid
  - r-pryr
  - r-curl
  - r-cachem
  - gflags
  - pygments
  - c-ares
  - r-scales
  - libcrc32c
  - krb5
  - fonts-conda-forge
  - r-backports
  - r-vctrs
  - r-htmlwidgets
  - cryptography
  - tktable
  - libcblas
  - zstd
  - r-labeling
  - r-ellipsis
  - font-ttf-dejavu-sans-mono
  - lerc
  - tzdata
  - libgcc-ng
  - libgoogle-cloud
  - _r-mutex
prefix: /users/k1342162/apps/miniconda3/envs/ukbkings
